#!/bin/bash

rm -rvf world

world_shp() {
  mkdir -p build
  curl -z build/ne_$1_admin_0_countries.zip -o build/ne_$1_admin_0_countries.zip http://naciscdn.org/naturalearth/$1/cultural/ne_$1_admin_0_countries.zip
  unzip -od build build/ne_$1_admin_0_countries.zip
  chmod a-x build/ne_$1_admin_0_countries.*
}

world() {
  world_shp $1
  mkdir -p world
  shp2json -n build/ne_$1_admin_0_countries.shp \
    | ndjson-map '(d.id = d.properties.iso_n3, d)' \
    > build/ne_$1_admin_0_countries.ndjson
  for i in MAR SAH; do
    grep '"adm0_a3":"'$i'"' build/ne_$1_admin_0_countries.ndjson > build/$i.json
    echo "remplacer les coordinates de $i par celles de fix-mar-sah.json"
  done
  geo2topo -q 1e5 -n countries=<( geostitch -n < build/ne_$1_admin_0_countries.fixed.ndjson) \
    | topomerge land=countries \
    > world/$1.json
  shp2json -n build/ne_$1_admin_0_countries.shp \
    | ndjson-map 'd.properties' \
    | ndjson-sort 'a.iso_a3.localeCompare(b.iso_a3)' \
    | json2tsv -n \
    > world/$1.tsv
}

world 110m
#world 50m
